### ISSUE TITLE
My bookmark content too big maybe

### ISSUE THREAD

**Issue by ucalyptus2** [imankulov/twitter-bookmarks-to-csv#1]
Hello @imankulov , here are my bookmarks https://gist.githubusercontent.com/forkbabu/2feecb06f8d3f3ff711d4141c3de20ea/raw/0d8e01c105aa883bc46cae4940101fc7ae64d0c0/bookmarks.txt
Your app doesn't work for this.

**Comment by imankulov** [comment]
Hey @forkbabu, it was supposed to be a one-off joke project and I'm surprised to see someone else found it useful 😄 This way or another, the issue should be fixed. I tested your bookmarks at https://twitter-bookmarks-to-csv.herokuapp.com/ and the export works. Cheers!

**Comment by ucalyptus2** [comment]
hi @imankulov, just as the upload touches 99%, I get an Application Error page. If the CSV is not too big, can you add it to this thread? sorry for the inconvenience.
![Screenshot from 2021-05-30 18-57-42](https://user-images.githubusercontent.com/8037297/120106005-f4aac280-c178-11eb-8531-e830325889ef.png)

**Comment by imankulov** [comment]
@forkbabu, here you go

[bookmarks.csv](https://github.com/imankulov/twitter-bookmarks-to-csv/files/6566272/bookmarks.csv)

**Comment by ucalyptus2** [comment]
@imankulov super helpful. Thanks a lot.
